spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${profile}

---

server:
  shutdown: graceful

spring:
  config:
    activate:
      on-profile: dev

  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    url: jdbc:mysql://${DB_ENDPOINT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        auto_quote_keyword: true
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true

